# Generated by Django 5.1.2 on 2024-11-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PROFORMA'), ('I', 'INVOICE')], max_length=1),
        ),
    ]
